import type { Metadata, Viewport } from 'next';
import { Suspense } from 'react';
import '@/styles/globals.css';
import { MobileDetector, Polyfill } from '@/components';
import { QueryProvider } from '@/providers';
import { cn, staticMetadata } from '@/utils';
import localFont from 'next/font/local';

export const metadata: Metadata = staticMetadata({
  title: 'Create Next App',
  description: 'Generated by create next app',
});

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  userScalable: false,
  viewportFit: 'cover',
  interactiveWidget: 'resizes-content',
};

const pretendard = localFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
  preload: false,
});

/**
 * App Router 의 루트 레이아웃.
 *
 * 모든 페이지를 감싸며, 다음 사이드 이펙트 / 마운트 포인트가 정해진 순서로 위치한다.
 * 1. `<Polyfill />` — core-js 폴리필을 가장 먼저 주입.
 * 2. `<QueryProvider>` — `@tanstack/react-query` 의 `QueryClientProvider`. Suspense 보다 바깥에 위치해야
 *    children 트리 어디서든 `useQuery` 가 동작한다.
 * 3. `<Suspense>{children}` — 페이지 트리. 로딩 경계의 기본 fallback 은 비워 둠.
 * 4. `<MobileDetector />` — User-Agent 분석 결과를 zustand 에 기록 (`isReady` 가 `true` 가 됨).
 * 5. `#next-app-portal` — `<Portal />` 컴포넌트가 children 을 포털링하는 마운트 포인트.
 *
 * `cn` 으로 합쳐진 body 클래스는 Pretendard 가변 폰트 변수, 한글 줄바꿈 규칙(`break-keep`),
 * 터치 스크롤 방향 제한(`touch-pan-y`), 사용자 텍스트 선택 비활성화(`select-none`) 등을 적용한다.
 */
export default function RootLayout({ children }: Readonly<LayoutProps<'/'>>) {
  return (
    <html lang="ko">
      <body
        className={cn(
          pretendard.variable,
          'touch-pan-y bg-background font-pretendard break-keep text-foreground antialiased select-none'
        )}
      >
        <Polyfill />

        <QueryProvider>
          <Suspense>{children}</Suspense>

          <MobileDetector />

          {/* For Portal Component */}
          <div id="next-app-portal" />
        </QueryProvider>
      </body>
    </html>
  );
}
