import type { Metadata } from 'next';
import { ReactNode } from 'react';
import '@/styles/global.scss';
import 'normalize.css';
import { MobileDetector, RecoilClient } from '@/components';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="ko">
      <body>
        <RecoilClient>
          <MobileDetector>{children}</MobileDetector>
        </RecoilClient>
      </body>
    </html>
  );
}
